---
name: Commit stage
run-name: ${{github.actor}} esta probando el commit
on:
    push:
        paths-ignore: 
            - 'docs/**'
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # Check out repo and set up Python   #
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.11.3
          poetry-version: 1.4.2

      # Run your actual job
      - name: Run unit tests
        run: |
          poetry run python ci/commit_stage.py

      - name: Build the application
        run: |
          poetry run python ci/build_stage.py
